aws_region          = "ap-southeast-2"
aws_account_id      = "171101346296"
aws_assume_role     = "TerraformAccessRole"
ecs_nlb_domain_name = "dev.alhardy.net"
private_namespace   = "alhardynet.local"
appmesh_name        = "alhardynet"